#include "uca-phantom-communicate.h"
#include "uca-phantom-variables.h"

#include <glib-object.h>

PhantomUnit variables[] = {
    {"info.sensor", G_TYPE_UINT, G_PARAM_READABLE, UNIT_INFO_SENSOR, "Type of sensor used."},
    {"info.snsversion", G_TYPE_UINT, G_PARAM_READABLE, UNIT_INFO_SNSVERSION, "Version number of the sensor."},
    {"info.cfa", G_TYPE_UINT, G_PARAM_READABLE, UNIT_INFO_CFA, "Type of color filter array deposited on the sensor."},
    {"info.filter", G_TYPE_UINT, G_PARAM_READABLE, UNIT_INFO_FILTER, "Additional filter used."},
    {"info.hwver", G_TYPE_UINT, G_PARAM_READABLE, UNIT_INFO_HWVER, "Current hardware version."},
    {"info.kernel", G_TYPE_UINT, G_PARAM_READABLE, UNIT_INFO_KERNEL, "Current kernel version."},
    {"info.swver", G_TYPE_UINT, G_PARAM_READABLE, UNIT_INFO_SWVER, "Current firmware version."},
    {"info.xver", G_TYPE_UINT, G_PARAM_READABLE, UNIT_INFO_XVER, "Current FPGA version."},
    {"info.model", G_TYPE_STRING, G_PARAM_READABLE, UNIT_INFO_MODEL, "Camera model."},
    {"info.pver", G_TYPE_UINT, G_PARAM_READABLE, UNIT_INFO_PVER, "Protocol version (16)."},
    {"info.sver", G_TYPE_UINT, G_PARAM_READABLE, UNIT_INFO_SVER, "System (kernel+filesystem) release number."},
    {"info.fver", G_TYPE_UINT, G_PARAM_READABLE, UNIT_INFO_FVER, "Firmware release number."},
    {"info.serial", G_TYPE_UINT, G_PARAM_READABLE, UNIT_INFO_SERIAL, "Camera serial number."},
    {"info.name", G_TYPE_STRING, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_INFO_NAME, "Camera name."},
    {"info.features", G_TYPE_STRING, G_PARAM_READABLE, UNIT_INFO_FEATURES, "A string of tokens separated by spaces which indicate if the camera supports certain features."},
    {"info.imgformats", G_TYPE_STRING, G_PARAM_READABLE, UNIT_INFO_IMGFORMATS, "Image formats supported by the img command."},
    {"info.videosystems", G_TYPE_STRING, G_PARAM_READABLE, UNIT_INFO_VIDEOSYSTEMS, "List of formats supported on the video output. The formats are specified by the codes used by the video.system variable."},
    {"info.maxcines", G_TYPE_UINT, G_PARAM_READABLE, UNIT_INFO_MAXCINES, "Maximum number of cines that can be allocated."},
    {"info.xmax", G_TYPE_UINT, G_PARAM_READABLE, UNIT_INFO_XMAX, "Maximum horizontal resolution (pixels)."},
    {"info.ymax", G_TYPE_UINT, G_PARAM_READABLE, UNIT_INFO_YMAX, "Maximum vertical resolution (pixels)."},
    {"info.xinc", G_TYPE_UINT, G_PARAM_READABLE, UNIT_INFO_XINC, "Horizontal increment; valid horizontal resolutions are a multiple of xinc."},
    {"info.yinc", G_TYPE_UINT, G_PARAM_READABLE, UNIT_INFO_YINC, "Vertical increment; valid vertical resolutions are a multiple of yinc."},
    {"info.winx", G_TYPE_UINT, G_PARAM_READABLE, UNIT_INFO_WINX, "Windows can start at multiples of winx pixels from the left sensor edge."},
    {"info.winy", G_TYPE_UINT, G_PARAM_READABLE, UNIT_INFO_WINY, "Windows can start at multiples of winy pixels from the top sensor edge."},
    {"info.kernsz", G_TYPE_UINT, G_PARAM_READABLE, UNIT_INFO_KERNSZ, "Size of acquisition kernel (in bytes); all image memory is allocated internally in kernel units. kernsz is used to transform that into bytes."},
    {"info.memsz", G_TYPE_UINT, G_PARAM_READABLE, UNIT_INFO_MEMSZ, "Size of installed memory in megabytes."},
    {"info.cinemem", G_TYPE_UINT, G_PARAM_READABLE, UNIT_INFO_CINEMEM, "Total amount of image memory available for cine storage in megabytes."},
    {"info.mdepths", G_TYPE_UINT, G_PARAM_READABLE, UNIT_INFO_MDEPTHS, "Bit mask describing the available memory depths in the camera. If the n-th bit of this field is set, then image data can be acquired using an n bits pixel size."},
    {"info.expdead", G_TYPE_UINT, G_PARAM_READABLE, UNIT_INFO_EXPDEAD, "Minimum interval between two exposures; the shutter has to stay \u201cclosed\u201d for this time, so the maximum exposure time is 1/rate - expdead."},
    {"info.minexp", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_INFO_MINEXP, "Minimum exposure the camera is capable of, in ns."},
    {"info.xblock", G_TYPE_UINT, G_PARAM_READABLE, UNIT_INFO_XBLOCK, "Number of x pixels the camera reads in a clock cycle."},
    {"info.yblock", G_TYPE_UINT, G_PARAM_READABLE, UNIT_INFO_YBLOCK, "Number of y pixels the camera reads in a clock cycle."},
    {"info.pixps", G_TYPE_UINT, G_PARAM_READABLE, UNIT_INFO_PIXPS, "Time to read one pixel in picoseconds."},
    {"info.rotps", G_TYPE_UINT, G_PARAM_READABLE, UNIT_INFO_ROTPS, "Row overhead time in picoseconds."},
    {"info.fotps", G_TYPE_UINT, G_PARAM_READABLE, UNIT_INFO_FOTPS, "Frame overhead time in picoseconds."},
    {"info.minfrate", G_TYPE_UINT, G_PARAM_READABLE, UNIT_INFO_MINFRATE, "Minimum framerate."},
    {"info.maxrate", G_TYPE_UINT, G_PARAM_READABLE, UNIT_INFO_MAXRATE, "Maximum framerate."},
    {"info.tmodel", G_TYPE_UINT, G_PARAM_READABLE, UNIT_INFO_TMODEL, "Timing model used by the camera. Valid values = 4."},
    {"info.magtp", G_TYPE_UINT, G_PARAM_READABLE, UNIT_INFO_MAGTP, "Maximum pixel troughoutput that the camera can send to the cinemag interface, in pixels/sec."},
    {"info.rtobyteps", G_TYPE_UINT, G_PARAM_READABLE, UNIT_INFO_RTOBYTEPS, "Duration of one byte in picoseconds."},
    {"info.rtopacket", G_TYPE_UINT, G_PARAM_READABLE, UNIT_INFO_RTOPACKET, "Size of a packet in bytes."},
    {"info.rtopacketovhead", G_TYPE_UINT, G_PARAM_READABLE, UNIT_INFO_RTOPACKETOVHEAD, "Overhead per packet in bytes."},
    {"info.rtofrovhead", G_TYPE_UINT, G_PARAM_READABLE, UNIT_INFO_RTOFROVHEAD, "Overhead per frame in bytes."},
    {"info.rtochannels", G_TYPE_UINT, G_PARAM_READABLE, UNIT_INFO_RTOCHANNELS, "Number of RTO channels."},
    {"info.basechroma", G_TYPE_FLOAT, G_PARAM_READABLE, UNIT_INFO_BASECHROMA, "Default chroma gain used when the color matrix is off."},
    {"info.baseei", G_TYPE_UINT, G_PARAM_READABLE, UNIT_INFO_BASEEI, "Base Exposure Index, in ISO units. Exposing for this index should result in a properly exposed image with the camera at minimum video gain, a neutral tone curve and a gamma of 2.2."},
    {"info.snstemp", G_TYPE_INT, G_PARAM_READABLE, UNIT_INFO_SNSTEMP, "Sensor die temperature."},
    {"info.tepower", G_TYPE_INT, G_PARAM_READABLE, UNIT_INFO_TEPOWER, "Amount of power used by the sensor thermoelectric cooler as a percentage of full cooling power. Negative power levels indicate that the sensor is being heated instead of being cooled."},
    {"info.camtemp", G_TYPE_INT, G_PARAM_READABLE, UNIT_INFO_CAMTEMP, "Camera temperature measured inside the body."},
    {"info.fanpower", G_TYPE_INT, G_PARAM_READABLE, UNIT_INFO_FANPOWER, "Fan speed as a percentage of maximum speed."},
    {"info.batti", G_TYPE_INT, G_PARAM_READABLE, UNIT_INFO_BATTI, "Battery current in milliamps."},
    {"info.battv", G_TYPE_UINT, G_PARAM_READABLE, UNIT_INFO_BATTV, "Battery voltage in millivolts."},
    {"info.battstate", G_TYPE_UINT, G_PARAM_READABLE, UNIT_INFO_BATTSTATE, "Battery status: 0=no battery, 1=charging, 2=full, 3 =discharging, 4=low."},
    {"info.batttimer", G_TYPE_UINT, G_PARAM_READABLE, UNIT_INFO_BATTTIMER, "Number of seconds until camera will turn down by itself, 0=stay on until battery empty."},
    {"info.genlockstat", G_TYPE_UINT, G_PARAM_READABLE, UNIT_INFO_GENLOCKSTAT, "State of genlock system: 0=poweroff, 1=idle, 2=measure line length, 3=wait for line lock, 4=measure field length, 5=enter field lock, 6=force field lock, 7=field lock check, 8=locked, 9=bad signal, 10=locked and time code present."},
    {"info.modes", G_TYPE_STRING, G_PARAM_READABLE, UNIT_INFO_MODES, "List of supported modes. The modes are assigned sequential numbers starting from zero, which correspond to the labels in this list. If a mode number is not used, the corresponding label is \u201cNA\u201d."},
    {"preset.tone1", G_TYPE_STRING, G_PARAM_READWRITE, UNIT_PRESET_TONE1, "Storage for tone curve presets."},
    {"preset.tone2", G_TYPE_STRING, G_PARAM_READWRITE, UNIT_PRESET_TONE2, "Storage for tone curve presets."},
    {"preset.tone3", G_TYPE_STRING, G_PARAM_READWRITE, UNIT_PRESET_TONE3, "Storage for tone curve presets."},
    {"preset.tone4", G_TYPE_STRING, G_PARAM_READWRITE, UNIT_PRESET_TONE4, "Storage for tone curve presets."},
    {"preset.matrix1", G_TYPE_STRING, G_PARAM_READWRITE, UNIT_PRESET_MATRIX1, "Storage for color matrix presets."},
    {"preset.matrix2", G_TYPE_STRING, G_PARAM_READWRITE, UNIT_PRESET_MATRIX2, "Storage for color matrix presets."},
    {"preset.matrix3", G_TYPE_STRING, G_PARAM_READWRITE, UNIT_PRESET_MATRIX3, "Storage for color matrix presets."},
    {"preset.matrix4", G_TYPE_STRING, G_PARAM_READWRITE, UNIT_PRESET_MATRIX4, "Storage for color matrix presets."},
    {"preset.filter1", G_TYPE_STRING, G_PARAM_READWRITE, UNIT_PRESET_FILTER1, "Storage for color filter presets."},
    {"preset.filter2", G_TYPE_STRING, G_PARAM_READWRITE, UNIT_PRESET_FILTER2, "Storage for color filter presets."},
    {"preset.filter3", G_TYPE_STRING, G_PARAM_READWRITE, UNIT_PRESET_FILTER3, "Storage for color filter presets."},
    {"preset.filter4", G_TYPE_STRING, G_PARAM_READWRITE, UNIT_PRESET_FILTER4, "Storage for color filter presets."},
    {"preset.ei1", G_TYPE_STRING, G_PARAM_READABLE, UNIT_PRESET_EI1, "Storage for EI-adjusting response curves."},
    {"preset.ei2", G_TYPE_STRING, G_PARAM_READABLE, UNIT_PRESET_EI2, "Storage for EI-adjusting response curves."},
    {"preset.ei3", G_TYPE_STRING, G_PARAM_READABLE, UNIT_PRESET_EI3, "Storage for EI-adjusting response curves."},
    {"preset.ei4", G_TYPE_STRING, G_PARAM_READABLE, UNIT_PRESET_EI4, "Storage for EI-adjusting response curves."},
    {"preset.ei5", G_TYPE_STRING, G_PARAM_READABLE, UNIT_PRESET_EI5, "Storage for EI-adjusting response curves."},
    {"preset.ei6", G_TYPE_STRING, G_PARAM_READABLE, UNIT_PRESET_EI6, "Storage for EI-adjusting response curves."},
    {"preset.ei7", G_TYPE_STRING, G_PARAM_READABLE, UNIT_PRESET_EI7, "Storage for EI-adjusting response curves."},
    {"preset.ei8", G_TYPE_STRING, G_PARAM_READABLE, UNIT_PRESET_EI8, "Storage for EI-adjusting response curves."},
    {"cam.syncimg", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_CAM_SYNCIMG, "Frame sync mode: when 0, the camera free-runs; when 1, it locks to the fsync input; when 2, it locks to the irig timebase; when 3, it locks to the video frame rate. For cameras with the tsync feature, syncimg = 5 sets the sync to trigger mode."},
    {"cam.frdelay", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_CAM_FRDELAY, "Delay between the sync reference moment and the start of exposure, in ns."},
    {"cam.rtoen", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_CAM_RTOEN, "1= enable the real time output, 0= disable."},
    {"cam.rtotfr", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_CAM_RTOTFR, "RTO test frame size in bytes."},
    {"cam.membpp", G_TYPE_UINT, G_PARAM_READABLE, UNIT_CAM_MEMBPP, "Bit depth into image memory. Can be changed via the acqmode command."},
    {"cam.trigpol", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_CAM_TRIGPOL, "Trigger polarity; when 0, the camera triggers on the falling edge of the trigger signal; when 1, on the rising edge. Cameras with the hvtrig feature set support two additional values, 2 and 3. With these values, the pullup to +5V on the trigger signal is disabled, and the nominal trigger input treshold becomes 6V instead of 1.5V. Triggering occurs on falling and rising edge respectively."},
    {"cam.trigfilt", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_CAM_TRIGFILT, "Minimum time in \u03bcs the trigger signal has to be asserted continuously in order to be recognised. In addition, the signal needs to have been continuously unasserted for at least four times this amount of time for a trigger to be accepted."},
    {"cam.startonacq", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_CAM_STARTONACQ, "When 1, the camera starts in waiting for trigger mode; when 0, it starts in preview mode to save power."},
    {"cam.aux1mode", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_CAM_AUX1MODE, "Function of the aux1 signal (pin 6): 0=strobe, 1=event, 2=memgate, 3=fsync."},
    {"cam.aux2mode", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_CAM_AUX2MODE, "Function of the aux2 signal (pin 5): 0=ready, 1=strobe, 2=aes/ebu out."},
    {"cam.aux3mode", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_CAM_AUX3MODE, "Function of the aux3 signal (pin 12): 0=irig out, 1=strobe."},
    {"cam.tsformat", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_CAM_TSFORMAT, "Timestamp format used in future recordings, as described in Section 5.12 ."},
    {"cam.tcmode", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_CAM_TCMODE, "Timecode mode( 0=irig, 1=smpte)."},
    {"cam.master", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_CAM_MASTER, "Serial number of the sync master. not used by the camera."},
    {"cam.apoffdis", G_TYPE_INT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_CAM_APOFFDIS, "Auto poweroff disable."},
    {"cam.longready", G_TYPE_UINT, G_PARAM_READABLE, UNIT_CAM_LONGREADY, "Ready becomes inactive at end of recording instead of trigger time."},
    {"cam.cines", G_TYPE_UINT, G_PARAM_READABLE, UNIT_CAM_CINES, "Number of recordable cines (partitions) as generated by the partition command."},
    {"cam.dark", G_TYPE_INT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_CAM_DARK, "Close (1) / Open (0) the mechanical shutter."},
    {"cam.tsetsns", G_TYPE_UINT, G_PARAM_READABLE, UNIT_CAM_TSETSNS, "Sensor temperature set point."},
    {"cam.tsetcam", G_TYPE_UINT, G_PARAM_READABLE, UNIT_CAM_TSETCAM, "Camera temperature set point."},
    {"cam.tz", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_CAM_TZ, "Difference in seconds between local time and UTC. Used when displaying local time on the OSD. All time values in the protocol are UTC."},
    {"cam.mode", G_TYPE_UINT, G_PARAM_READABLE, UNIT_CAM_MODE, "Current camera mode number. The corresponding mode name can be found using info.modes. Use iload to change the mode."},
    {"auto.videoplay", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_AUTO_VIDEOPLAY, "When non-zero, the camera will play back the recorded cine on video immediately after the recording ends and the autosave operations are finished. A rec command or the pretrigger signal will abort a video play operation."},
    {"auto.flashsave", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_AUTO_FLASHSAVE, "When non-zero, a camera will save the just-recorded cine to a cinemag. If the cinemag fills up (or is not installed), this flag is cleared."},
    {"auto.filesave", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_AUTO_FILESAVE, "When non-zero, the camera will save the just-recorded cine to a attached storage device. If an error occurs during save, this flag is cleared. When both flashsave and filesave are set, a file save operation is not performed if the flash save was successful."},
    {"auto.acqrestart", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_AUTO_ACQRESTART, "When non-zero, the camera will restart acquisition after a sucessfull automatic save."},
    {"auto.bref", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_AUTO_BREF, "When non-zero, the camera will take a new black reference (CSR) at the start of each recording."},
    {"auto.firstframe", G_TYPE_INT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_AUTO_FIRSTFRAME, "The first frame of the region that is to be saved and/or played on video."},
    {"auto.lastframe", G_TYPE_INT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_AUTO_LASTFRAME, "The last frame of the region that is to be saved and/or played on video."},
    {"auto.loops", G_TYPE_UINT, G_PARAM_READWRITE, UNIT_AUTO_LOOPS, "A non-zero value is the loop counter for video play back. When the value is zero, the behavior of the camera is determined by the value of the auto.acqrestart field as follows: if auto.acqrestart is zero, then the video playback loops forever; if auto.acqrestart is non-zero, then the video is played back only once and afterwards the acquisition is restarted. A non-zero value N means to play the video N times."},
    {"auto.speed", G_TYPE_UINT, G_PARAM_READWRITE, UNIT_AUTO_SPEED, "Speed of video play back (number of times each frame will get played)."},
    {"auto.progress", G_TYPE_UINT, G_PARAM_READABLE, UNIT_AUTO_PROGRESS, "The number of frames still to do by the auto process."},
    {"auto.bref_progress", G_TYPE_UINT, G_PARAM_READABLE, UNIT_AUTO_BREFPROGRESS, "The bref command accumulates the black reference for a total of eight frames. This is number of frames left."},
    {"auto.trigger.x", G_TYPE_INT, G_PARAM_READWRITE, UNIT_AUTO_TRIGGER_X, "X coordinate of the center of the autotrigger region, relative to the center of the image."},
    {"auto.trigger.y", G_TYPE_INT, G_PARAM_READWRITE, UNIT_AUTO_TRIGGER_Y, "Y coordinate of the center of the autotrigger region, relative to the center of the image. y values increase towards the bottom of the image."},
    {"auto.trigger.w", G_TYPE_UINT, G_PARAM_READWRITE, UNIT_AUTO_TRIGGER_W, "Width of the autotrigger region. When the width is zero, a default value will be used. the default value is one quarter of the image width or 128 pixels, whichever is larger."},
    {"auto.trigger.h", G_TYPE_UINT, G_PARAM_READWRITE, UNIT_AUTO_TRIGGER_H, "Height of the autotrigger region. When the height is zero, a default value will be used. the default value is one quarter of the image height or 16 pixels, whichever is larger."},
    {"auto.trigger.threshold", G_TYPE_UINT, G_PARAM_READWRITE, UNIT_AUTO_TRIGGER_THRESHOLD, "Amount a pixel value must change in order to be counted as an active pixel for autotrigger purposes. A value of 100 would require a change of approximately half of the full swing of the camera. A typical threshold setting would be 10."},
    {"auto.trigger.area", G_TYPE_UINT, G_PARAM_READWRITE, UNIT_AUTO_TRIGGER_AREA, "Percentage of the area of the autotrigger region that must be active in order for an autotrigger event to be generated. A typical percentage value is 10."},
    {"auto.trigger.speed", G_TYPE_UINT, G_PARAM_READWRITE, UNIT_AUTO_TRIGGER_SPEED, "Number of frames between updates of the autotrigger reference memory. A value larger than 1 allows the trigger to activate on slower events. Image changes are evaluated over a time interval of auto.trigger.speed/frame rate."},
    {"auto.trigger.mode", G_TYPE_UINT, G_PARAM_READWRITE, UNIT_AUTO_TRIGGER_MODE, "Operating mode of the autotrigger."},
    {"defc.res", G_TYPE_STRING, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_DEFC_RES, "Image size in pixels."},
    {"defc.rate", G_TYPE_FLOAT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_DEFC_RATE, "Frame rate in pictures per second."},
    {"defc.exp", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_DEFC_EXP, "Exposure time, in ns."},
    {"defc.edrexp", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_DEFC_EDREXP, "EDR exposure time in ns."},
    {"defc.ptframes", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_DEFC_PTFRAMES, "Number of post-trigger frames."},
    {"defc.shoff", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_DEFC_SHOFF, "Shutter off: Always use maximum possible exposure and minimum straddle time."},
    {"defc.ramp", G_TYPE_STRING, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_DEFC_RAMP, "Frame rate ramping specification string."},
    {"defc.bcount", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_DEFC_BCOUNT, "Number of frames per burst. When 0 or 1, the frame burst mode is disabled."},
    {"defc.bperiod", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_DEFC_BPERIOD, "Time interval in ns between successive frames in a burst."},
    {"defc.hqenable", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_DEFC_HQENABLE, "Enable HQ acquisition mode."},
    {"defc.decimation", G_TYPE_UINT, G_PARAM_READWRITE, UNIT_DEFC_DECIMATION, "Ratio between the frame rate going into camera RAM and the rate being output on RTO or the cinemag interface."},
    {"defc.frcount", G_TYPE_UINT, G_PARAM_READABLE, UNIT_DEFC_FRCOUNT, "Number of frames that can be stored in a cine (either the currently active cine, or the first cine in the table that is available for recording in case the preview cine is the currently active cine)."},
    {"defc.frsize", G_TYPE_UINT, G_PARAM_READABLE, UNIT_DEFC_FRSIZE, "Amount of space required to store a frame of the size specified in defc, in kernels. Dividing the value of a cine\u2019s frspace value to defc.frsize yields the capacity of that cine in frames."},
    {"defc.aexpmode", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_DEFC_AEXPMODE, "Autoexposure mode: 0=off, 1=average, 2=spot, 3=center-weighted."},
    {"defc.aexpcomp", G_TYPE_FLOAT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_DEFC_AEXPCOMP, "Autoexposure compensation in stops. Positive values increase the exposure."},
    {"defc.meta.ox", G_TYPE_INT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_DEFC_META_OX, "X offset of window from the camera frame center for application software crop and scale, in camera pixels."},
    {"defc.meta.oy", G_TYPE_INT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_DEFC_META_OY, "Y offset of window."},
    {"defc.meta.w", G_TYPE_INT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_DEFC_META_W, "Window width in camera pixels."},
    {"defc.meta.h", G_TYPE_INT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_DEFC_META_H, "Window height in camera pixels."},
    {"defc.meta.ow", G_TYPE_INT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_DEFC_META_OW, "Window width after software crop and scale in pixels."},
    {"defc.meta.oh", G_TYPE_INT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_DEFC_META_OH, "Window height after software crop and scale in pixels."},
    {"defc.meta.crop", G_TYPE_INT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_DEFC_META_CROP, "Enable software crop."},
    {"defc.meta.oh", G_TYPE_INT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_DEFC_META_OH_2, "Enable software scale."},
    {"c%d.state", G_TYPE_STRING, G_PARAM_READABLE, UNIT_C_STATE, "Cine state."},
    {"c%d.frcount", G_TYPE_UINT, G_PARAM_READABLE, UNIT_C_FRCOUNT, "Number of frames recorded."},
    {"c%d.firstfr", G_TYPE_INT, G_PARAM_READABLE, UNIT_C_FIRSTFR, "Index of the first frame in the cine that can be played."},
    {"c%d.lastfr", G_TYPE_INT, G_PARAM_READABLE, UNIT_C_LASTFR, "Index of the last frame in the cine that can be played."},
    {"c%d.format", G_TYPE_INT, G_PARAM_READABLE, UNIT_C_FORMAT, "For non-RAM cines, the format the cine was saved in, which is also the only format it can be downloaded in. For RAM cines the values of this field is undefined, and they cab be downloaded in any format supported by the camera."},
    {"c%d.in", G_TYPE_INT, G_PARAM_READABLE, UNIT_C_IN, "Current in point for cine playback. The values of the in and out points are set to the first and last image in the cine when the cine becomes stored. They can later be changed to reflect the interesting region of the cine."},
    {"c%d.out", G_TYPE_INT, G_PARAM_READABLE, UNIT_C_OUT, "Current out point for cine playback."},
    {"c%d.start", G_TYPE_UINT, G_PARAM_READABLE, UNIT_C_START, "Start address of the image buffer (in kernels)."},
    {"c%d.len", G_TYPE_UINT, G_PARAM_READABLE, UNIT_C_LEN, "Length of the cine buffer (in kernels). The start and len are mostly used for debugging purposes."},
    {"c%d.frsize", G_TYPE_UINT, G_PARAM_READABLE, UNIT_C_FRSIZE, "frame size at the cine\u2019s resolution, in kernels. This value is invalid if the cine is not active or stored."},
    {"c%d.frspace", G_TYPE_UINT, G_PARAM_READABLE, UNIT_C_FRSPACE, "Cine memory region capacity in kernels. Dividing this value by defc.frsize yields the cine capacity in frames."},
    {"c%d.trigtime.secs", G_TYPE_UINT, G_PARAM_READABLE, UNIT_C_TRIGTIME_SECS, "Time when cine was triggered, in seconds since 1970."},
    {"c%d.trigtime.frac", G_TYPE_UINT, G_PARAM_READABLE, UNIT_C_TRIGTIME_FRAC, "Fraction of second of the trigger time (\u03bcs)."},
    {"c%d.meta.pbrate", G_TYPE_FLOAT, G_PARAM_READABLE, UNIT_C_META_PBRATE, "Default playback rate of cine, determined by the video format at the time of the recording."},
    {"c%d.meta.tcrate", G_TYPE_FLOAT, G_PARAM_READABLE, UNIT_C_META_TCRATE, "Time code rate, determined by video format."},
    {"c%d.meta.uuid", G_TYPE_STRING, G_PARAM_READABLE, UNIT_C_META_UUID, "Unique identifier for the cine."},
    {"c%d.meta.system", G_TYPE_UINT, G_PARAM_READABLE, UNIT_C_META_SYSTEM, "Value of the video.system field at the time of recording."},
    {"c%d.meta.trigtc", G_TYPE_STRING, G_PARAM_READABLE, UNIT_C_META_TRIGTC, "Tigger timecode in hh:mm:ss.ss format."},
    {"c%d.meta.pax", G_TYPE_UINT, G_PARAM_READABLE, UNIT_C_META_PAX, "Production area rectangle width. This and the next 9 variables are copies of the corresponding fields of the video structure, made at the time of recording."},
    {"c%d.meta.pay", G_TYPE_UINT, G_PARAM_READABLE, UNIT_C_META_PAY, "Production area rectangle height."},
    {"c%d.meta.paox", G_TYPE_UINT, G_PARAM_READABLE, UNIT_C_META_PAOX, "Production area X offset from center."},
    {"c%d.meta.paoy", G_TYPE_UINT, G_PARAM_READABLE, UNIT_C_META_PAOY, "Production area Y offset from center."},
    {"c%d.meta.vox", G_TYPE_UINT, G_PARAM_READABLE, UNIT_C_META_VOX, "Video output scaling (X offset from center)."},
    {"c%d.meta.voy", G_TYPE_UINT, G_PARAM_READABLE, UNIT_C_META_VOY, "Video output scaling (Y offset from center)."},
    {"c%d.meta.vow", G_TYPE_UINT, G_PARAM_READABLE, UNIT_C_META_VOW, "Video output scaling (output width)."},
    {"c%d.meta.voh", G_TYPE_UINT, G_PARAM_READABLE, UNIT_C_META_VOH, "Video output scaling (output height)."},
    {"c%d.meta.vw", G_TYPE_UINT, G_PARAM_READABLE, UNIT_C_META_VW, "Video output scaling (input width)."},
    {"c%d.meta.vh", G_TYPE_UINT, G_PARAM_READABLE, UNIT_C_META_VH, "Video output scaling (input height)."},
    {"c%d.meta.ox", G_TYPE_UINT, G_PARAM_READABLE, UNIT_C_META_OX, "Software image scale and crop (X offset from center). This and the next seven variables come from defc.meta."},
    {"c%d.meta.oy", G_TYPE_UINT, G_PARAM_READABLE, UNIT_C_META_OY, "Software image scale and crop (Y offset from center)."},
    {"c%d.meta.ow", G_TYPE_UINT, G_PARAM_READABLE, UNIT_C_META_OW, "Software image scale and crop (output width)."},
    {"c%d.meta.oh", G_TYPE_UINT, G_PARAM_READABLE, UNIT_C_META_OH, "Software image scale and crop (output height)."},
    {"c%d.meta.w", G_TYPE_UINT, G_PARAM_READABLE, UNIT_C_META_W, "Software image scale and crop (input width)."},
    {"c%d.meta.h", G_TYPE_UINT, G_PARAM_READABLE, UNIT_C_META_H, "Software image scale and crop (input height)."},
    {"c%d.meta.crop", G_TYPE_UINT, G_PARAM_READABLE, UNIT_C_META_CROP, "Enable image crop by software."},
    {"c%d.meta.resize", G_TYPE_UINT, G_PARAM_READABLE, UNIT_C_META_RESIZE, "Enable image scale by software."},
    {"c%d.meta.gps", G_TYPE_STRING, G_PARAM_READABLE, UNIT_C_META_GPS, "Copy of irig.gps made at the time the cine recording ended."},
    {"irig.sec", G_TYPE_UINT, G_PARAM_READABLE, UNIT_IRIG_SEC, "Current time of the camera timebase in seconds since 1970."},
    {"irig.yearbegin", G_TYPE_UINT, G_PARAM_READABLE, UNIT_IRIG_YEARBEGIN, "Number of seconds since 1970 to the beginning of the current year; used to add year information to the irig time stamps."},
    {"irig.flags", G_TYPE_STRING, G_PARAM_READABLE, UNIT_IRIG_FLAGS, "Status flags for the timebase unit; see below."},
    {"irig.signal", G_TYPE_STRING, G_PARAM_READABLE, UNIT_IRIG_SIGNAL, "Textual description of the incoming time code signal."},
    {"irig.gps", G_TYPE_STRING, G_PARAM_READABLE, UNIT_IRIG_GPS, "Current position and status info as received from a GPS receiver. It contains the GPRMC, GPGGA and GPGSA messages"},
    {"irig.range", G_TYPE_STRING, G_PARAM_READABLE, UNIT_IRIG_RANGE, "String representation of the current range data being received."},
    {"meta.name", G_TYPE_STRING, G_PARAM_READWRITE, UNIT_META_NAME, "A 256 bytes string used to name the recorded cines. Succesive names are automatically generated by appending an index to meta.name. If meta.name already contains a trailing numeric value, this value is used as a start value for the index."},
    {"meta.lens", G_TYPE_STRING, G_PARAM_READABLE, UNIT_META_LENS, "focal length range and aperture range of a supported \u201cintelligent\u201d lens. When no active lens mount is fitted, or no lens is mounted, this field is set to a null string."},
    {"meta.fstop", G_TYPE_FLOAT, G_PARAM_READABLE, UNIT_META_FSTOP, "current fstop value of the fitted lens."},
    {"meta.flen", G_TYPE_FLOAT, G_PARAM_READABLE, UNIT_META_FLEN, "current focal length value of the fitted lens."},
    {"meta.comment", G_TYPE_STRING, G_PARAM_READWRITE, UNIT_META_COMMENT, "a 4 Kbytes comment string saved with the cine."},
    {"meta.xset", G_TYPE_STRING, G_PARAM_READWRITE, UNIT_META_XSET, "a 4 Kbytes string used for storing external applications settings."},
    {"video.system", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_VIDEO_SYSTEM, "Video format code."},
    {"video.output", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_VIDEO_OUTPUT, "Sets video output mode (camera-dependent)."},
    {"video.fields", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_VIDEO_FIELDS, "Not used"},
    {"video.widescreen", G_TYPE_FLOAT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_VIDEO_WIDESCREEN, "Set anamorphic desqueeze ratio for some cameras and video modes. A value betwee 0 and 1.0 disables desqueeze."},
    {"video.genlock", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_VIDEO_GENLOCK, "1 = Enable genlock. 3= Enable genlock and reading the VITC (linear time code) from the video return input."},
    {"video.vfmode", G_TYPE_UINT, G_PARAM_READWRITE, UNIT_VIDEO_VFMODE, "Viewfinder mode. 0=normal, 1=threshold, 2=zoom, 4=zoom more, 8=show return signal (on some cameras)."},
    {"video.osddis", G_TYPE_INT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_VIDEO_OSDDIS, "Turns off the OSD on selected outputs. 1: OSD off on analog and HSDSI1; 2: OSD off on HDSDI2; 3: OSD off on all outputs."},
    {"video.osdut", G_TYPE_BOOLEAN, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_VIDEO_OSDUT, "Show UT timestamps instead of local time on the OSD."},
    {"video.pax", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_VIDEO_PAX, "Production area X size."},
    {"video.pay", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_VIDEO_PAY, "Production area Y size."},
    {"video.paox", G_TYPE_INT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_VIDEO_PAOX, "Production area X offset from center of picture."},
    {"video.paoy", G_TYPE_INT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_VIDEO_PAOY, "Production area Y offset"},
    {"video.uzoom", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_VIDEO_UZOOM, "Sets image scaling: 0=zoom to fit, 1=1:1 (or 1:2 for 4k pictures and HD/2k outputs); larger values scale proportionally."},
    {"video.vox", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_VIDEO_VOX, "Origin of picture window in from the left edge of the video raster."},
    {"video.voy", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_VIDEO_VOY, "Origin of the picture window from the top edge of the video raster."},
    {"video.vow", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_VIDEO_VOW, "Width of picture window in video raster pixels."},
    {"video.voh", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_VIDEO_VOH, "Height of picture window in video raster pixels."},
    {"video.vw", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_VIDEO_VW, "Width of picture window in camera pixels."},
    {"video.vh", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_VIDEO_VH, "Height of picture window in camera pixels."},
    {"video.adj.red", G_TYPE_FLOAT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_VIDEO_ADJ_RED, "Gain of red channel at output of RGB matrix."},
    {"video.adj.green", G_TYPE_FLOAT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_VIDEO_ADJ_GREEN, "Gain of green channel."},
    {"video.adj.blue", G_TYPE_FLOAT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_VIDEO_ADJ_BLUE, "Gain of blue channel."},
    {"video.adj.toe", G_TYPE_FLOAT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_VIDEO_ADJ_TOE, "Control the gamma curve in the blacks. A value of 1.0 is the default, and matches the gamma curve of previos versions. Decreasing toe lifts the blacks, while increasing it compresses them."},
    {"video.adj.gamma", G_TYPE_FLOAT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_VIDEO_ADJ_GAMMA, "Global gamma for video output. A value of 2.2 makes the camera use a REC709 gamma curve."},
    {"video.adj.rgamma", G_TYPE_FLOAT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_VIDEO_ADJ_RGAMMA, "Difference between red channel gamma and overall gamma for video output."},
    {"video.adj.bgamma", G_TYPE_FLOAT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_VIDEO_ADJ_BGAMMA, "Difference between blue channel gamma and overall gamma for video output."},
    {"video.adj.gain", G_TYPE_FLOAT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_VIDEO_ADJ_GAIN, "Global video gain."},
    {"video.adj.offset", G_TYPE_FLOAT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_VIDEO_ADJ_OFFSET, "Video black level, before gamma LUTs but after white balance."},
    {"video.adj.flare", G_TYPE_FLOAT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_VIDEO_ADJ_FLARE, "Flare adjustement, offset before white balance."},
    {"video.adj.hue", G_TYPE_FLOAT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_VIDEO_ADJ_HUE, "REMOVE Hue angle adjustement."},
    {"video.adj.sat", G_TYPE_FLOAT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_VIDEO_ADJ_SAT, "Color saturation adjustement in linear space."},
    {"video.adj.rped", G_TYPE_FLOAT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_VIDEO_ADJ_RPED, "R channel pedestal."},
    {"video.adj.gped", G_TYPE_FLOAT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_VIDEO_ADJ_GPED, "G channel pedestal."},
    {"video.adj.bped", G_TYPE_FLOAT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_VIDEO_ADJ_BPED, "B channel pedestal."},
    {"video.adj.chroma", G_TYPE_FLOAT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_VIDEO_ADJ_CHROMA, "Chroma gain in YCrCb space."},
    {"video.adj.tone", G_TYPE_STRING, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_VIDEO_ADJ_TONE, "List of x, y points defining a tone curve for the camera. The list is completed with the implicit points of 0, 0 and 1, 1, and then a tone curve is generated as a cubic spline through the given points. The tone curve is applied to the image after the gamma LUTs."},
    {"video.adj.matrix", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_VIDEO_ADJ_MATRIX, "Enable color matrix. When 0, neither the calibration nor the user matrix is applied. However, the white balance component of the calibration matrix is still applied."},
    {"video.adj.log", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_VIDEO_ADJ_LOG, "Enable log mode for video outputs. A value of zero disables the log mode; Values of 1, 2 etc select different log curves for the outputs driven by the video pipeline A. In log mode, gain, gamma, the pedestals, r/g/b gains, offset and flare are inactive."},
    {"video.adj.sdimin", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_VIDEO_ADJ_SDIMIN, "Lower clamp value for video outputs (10-bit value). The nominal black level of the outputs does not change with sdimin, and is fixed at 64."},
    {"video.adj.sdimax", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_VIDEO_ADJ_SDIMAX, "Upper clamp value for video outputs (10-bit value). The image is scaled so that the white point is at sdimax."},
    {"video.adj.cmatrix", G_TYPE_STRING, G_PARAM_READABLE, UNIT_VIDEO_ADJ_CMATRIX, "Camera calibration matrix. This matrix is calculated by the camera from the contents of hw.colorcal and wbtemp and wbcc. It results in the output of the camera being converted to the REC709 colorimetry. cmatrix is a full RGB matrix, which specifies both a white balance operation and a color correction matrix. The camera separates the matrix into the two operations before applying them."},
    {"video.adj.filter", G_TYPE_STRING, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_VIDEO_ADJ_FILTER, "Filter calibration matrix. A string with the same format as hw.colorcal which describes the effect of a filter to the camera\u2019s color correction and white balance."},
    {"video.adj.umatrix", G_TYPE_STRING, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_VIDEO_ADJ_UMATRIX, "User RGB matrix, applied on the output of the calibration matrix."},
    {"video.adj.wbtemp", G_TYPE_FLOAT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_VIDEO_ADJ_WBTEMP, "White balance temperature. Temperature the camera is white balanced to, in Kelvins. Used to adjust red/blue balance."},
    {"video.adj.wbcc", G_TYPE_FLOAT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_VIDEO_ADJ_WBCC, "White balance color compensating index value. Used to adjust green/magenta balance."},
    {"video.adj.wbred", G_TYPE_FLOAT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_VIDEO_ADJ_WBRED, "White balance gain (red/green ratio). This variable shows the red/green white balance gain. If set, new wbtemp and wbcc values will be calculated to match the gain."},
    {"video.adj.wbblue", G_TYPE_FLOAT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_VIDEO_ADJ_WBBlUE, "White balance gain (blue/green ratio). Used together with wbred."},
    {"video.adj.mmsat", G_TYPE_STRING, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_VIDEO_ADJ_MMSAT, "List of 24 saturation values for multi-matrix color correction. Active when the \u201cmm24\u201d feature is set. Each value is the saturation factor for the respective axis. Set to a null string to disable. Individual axes can be set using the mmset command."},
    {"video.adj.mmhue", G_TYPE_STRING, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_VIDEO_ADJ_MMHUE, "List of 24 hue corrections (in degrees) for multi-matrix color correction. Active when the \u201cmm24\u201d feature is set. Each value is the hue angle for the respective axis. Set to a null string to disable. Individual axes can be set using the mmset command."},
    {"video.adj.edgeg", G_TYPE_FLOAT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_VIDEO_ADJ_EDGEG, "Edge enhancement gain, for cameras with the \u201cedge\u201d feature. A value of zero will turn the edge enhancement filter off. Values of 1, 1.5, 2, etc will increase the amount of sharpening."},
    {"video.adj.edger", G_TYPE_FLOAT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_VIDEO_ADJ_EDGER, "Edge enhancement filter radius, for cameras with the \u201cedge\u201d feature. The radius is set in pixels, with common settings in the range of 1..3."},
    {"video.adj.edgeth", G_TYPE_FLOAT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_VIDEO_ADJ_EDGETH, "Edge enhancement threshold, for cameras with the \u201cedge\u201d feature. The threshold below which there is no sharpening applied, expressed relative to full scale. Setting a threshold prevents the edge enhancement filter from increasing the noise. Too large a value will make the image look \u201cplasticky\u201d. Common settings are 0.005 for a well exposed image, or 0.01-0.02 for images that have been gained up and are more noisy."},
    {"video.play.live", G_TYPE_UINT, G_PARAM_READWRITE, UNIT_VIDEO_PLAY_LIVE, "When 1, the video output is in live mode. When 0, it is in playback mode. Setting this variable to 1 puts the video output in live mode. To start a playback, use a vplay command rather than setting this to 0."},
    {"video.play.cine", G_TYPE_UINT, G_PARAM_READABLE, UNIT_VIDEO_PLAY_CINE, "Number of the cine used for playback. Valid only in playback mode."},
    {"video.play.mag", G_TYPE_UINT, G_PARAM_READABLE, UNIT_VIDEO_PLAY_MAG, "Cine in video.play.cine is a cinemag cine when this variable is 1. Valid only in playback mode."},
    {"video.play.fn", G_TYPE_INT, G_PARAM_READABLE, UNIT_VIDEO_PLAY_FN, "Current frame number. Valid only in playback mode."},
    {"video.play.in", G_TYPE_INT, G_PARAM_READABLE, UNIT_VIDEO_PLAY_IN, "Playback operation in point. Valid only in playback mode."},
    {"video.play.out", G_TYPE_INT, G_PARAM_READABLE, UNIT_VIDEO_PLAY_OUT, "Playback operation out point. Valid only in playback mode."},
    {"video.play.speed", G_TYPE_UINT, G_PARAM_READWRITE, UNIT_VIDEO_PLAY_SPEED, "Number of fields before the playback frame is updated."},
    {"video.play.step", G_TYPE_INT, G_PARAM_READWRITE, UNIT_VIDEO_PLAY_STEP, "Amount by which the frame number is incremented/decremented for each frame update in playback mode. The effective video playback rate is the video format\u2019s pbrate * step / speed. For backward playback, use negative values for step. For still image, set step to zero."},
    {"video.play.frcount", G_TYPE_UINT, G_PARAM_READABLE, UNIT_VIDEO_PLAY_FRCOUNT, "Number of frames remaining from the current playback operation."},
    {"eth.ip", G_TYPE_STRING, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_ETH_IP, "IP address."},
    {"eth.netmask", G_TYPE_STRING, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_ETH_NETMASK, "Network mask."},
    {"eth.broadcast", G_TYPE_STRING, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_ETH_BROADCAST, "Broadcast mask."},
    {"eth.gateway", G_TYPE_STRING, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_ETH_GATEWAY, "Address of default gateway."},
    {"eth.mtu", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_ETH_MTU, "MTU used by the camera."},
    {"eth.xip", G_TYPE_STRING, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_ETH_XIP, "IP address for the 10GE."},
    {"eth.xnetmask", G_TYPE_STRING, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_ETH_XNETMASK, "Network mask for the 10GE."},
    {"eth.xbroadcast", G_TYPE_STRING, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_ETH_XBROADCAST, "Broadcast mask for the 10GE."},
    {"mag.state", G_TYPE_UINT, G_PARAM_READABLE, UNIT_MAG_STATE, "Status of the cinemag subsystem."},
    {"mag.progress", G_TYPE_UINT, G_PARAM_READABLE, UNIT_MAG_PROGRESS, "Progress indicator for various operations; when the decrementing value reaches zero, the operation is completed."},
    {"mag.protect", G_TYPE_UINT, G_PARAM_READABLE, UNIT_MAG_PROTECT, "The attached cinemag has the erase protect switch on."},
    {"mag.size", G_TYPE_UINT, G_PARAM_READABLE, UNIT_MAG_SIZE, "Size of the attached cinemag in kB."},
    {"mag.used", G_TYPE_UINT, G_PARAM_READABLE, UNIT_MAG_USED, "Amount of space used in the attached cinemag, in kB."},
    {"mag.takes", G_TYPE_UINT, G_PARAM_READABLE, UNIT_MAG_TAKES, "The number of cines stored to the attached cinemag."},
    {"mag.version", G_TYPE_UINT, G_PARAM_READABLE, UNIT_MAG_VERSION, "Cinemag firmware version."},
    {"mag.id", G_TYPE_STRING, G_PARAM_READABLE, UNIT_MAG_ID, "Textual description of device attached to the cinemag socket."},
    {"mag.runstop", G_TYPE_INT, G_PARAM_READWRITE, UNIT_MAG_RUNSTOP, "Enable direct recording to cinemag."},
    {"mag.type", G_TYPE_UINT, G_PARAM_READABLE, UNIT_MAG_TYPE, "Identification code for device attached to the cinemag socket."},
    {"cf.state", G_TYPE_INT, G_PARAM_READABLE, UNIT_CF_STATE, "status of the storage device( see below)."},
    {"cf.action", G_TYPE_UINT, G_PARAM_READABLE, UNIT_CF_ACTION, "number of active requests on the storage device."},
    {"cf.size", G_TYPE_UINT, G_PARAM_READABLE, UNIT_CF_SIZE, "Size of the currently attached storage device, in kB."},
    {"cf.used", G_TYPE_UINT, G_PARAM_READABLE, UNIT_CF_USED, "Size of the used space on the currently attached storage device, in kB."},
    {"cf.progress", G_TYPE_UINT, G_PARAM_READABLE, UNIT_CF_PROGRESS, "Decrementing counter showing the completion status of the current save operation."},
    {"cf.errcode", G_TYPE_UINT, G_PARAM_READABLE, UNIT_CF_ERRCODE, "Storage device error code."},
    {"usets.nsets", G_TYPE_UINT, G_PARAM_READABLE, UNIT_USETS_NSETS, "Number of available sets."},
    {"usets.valid%d", G_TYPE_BOOLEAN, G_PARAM_READABLE, UNIT_USETS_VALID_NUMBER, "Status information for set#. When 1, a properly formatted settings block was found at the respective location."},
    // No touchy
    // {"hw.vpix", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_HW_VPIX, ""},
    // {"hw.vpixl", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_HW_VPIXL, ""},
    // {"hw.vmemh", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_HW_VMEMH, ""},
    // {"hw.vmeml", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_HW_VMEML, ""},
    // {"hw.vresh", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_HW_VRESH, ""},
    // {"hw.vresl", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_HW_VRESL, ""},
    // {"hw.vresds", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_HW_VRESDS, ""},
    // {"hw.dcblack", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_HW_DCBLACK, ""},
    // {"hw.bbias", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_HW_BBIAS, ""},
    // {"hw.tbias", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_HW_TBIAS, ""},
    // {"hw.trbias", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_HW_TRBIAS, ""},
    // {"hw.brbias", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_HW_BRBIAS, ""},
    // {"hw.vmlpred", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_HW_VMLPRED, ""},
    // {"hw.prepw", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_HW_PREPW, ""},
    // {"hw.presmpd", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_HW_PRESMPD, ""},
    // {"hw.smppw", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_HW_SMPPW, ""},
    // {"hw.smpvmhd", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_HW_SMPVMHD, ""},
    // {"hw.vmhresd", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_HW_VMHRESD, ""},
    // {"hw.respw", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_HW_RESPW, ""},
    // {"hw.reswait", G_TYPE_UINT, G_PARAM_READWRITE, UNIT_HW_RESWAIT, ""},
    // {"hw.expadj", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_HW_EXPADJ, ""},
    // {"hw.sel2w", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_HW_SEL2W, ""},
    // {"hw.shkolmode", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_HW_SHKOLMODE, ""},
    // {"hw.reslong", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_HW_RESLONG, ""},
    // {"hw.snsflags", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_HW_SNSFLAGS, ""},
    // {"hw.nsfload", G_TYPE_INT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_HW_NSFLOAD, ""},
    // {"hw.colload", G_TYPE_INT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_HW_COLLOAD, ""},
    // {"hw.outload", G_TYPE_INT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_HW_OUTLOAD, ""},
    // {"hw.freqtrim", G_TYPE_INT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_HW_FREQTRIM, ""},
    // {"hw.irigphase", G_TYPE_INT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_HW_IRIGPHASE, ""},
    // {"hw.irigmodphase", G_TYPE_INT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_HW_IRIGMODPHASE, ""},
    // {"hw.mcode", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_HW_MCODE, ""},
    // {"hw.memphase", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_HW_MEMPHASE, ""},
    // {"hw.memflags", G_TYPE_INT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_HW_MEMFLAGS, ""},
    // {"hw.adphase", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_HW_ADPHASE, ""},
    // {"hw.adcflags", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_HW_ADCFLAGS, ""},
    // {"hw.dcphase", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_HW_DCPHASE, ""},
    // {"hw.touchdx", G_TYPE_INT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_HW_TOUCHDX, ""},
    // {"hw.touchdy", G_TYPE_INT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_HW_TOUCHDY, ""},
    // {"hw.touchsx", G_TYPE_INT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_HW_TOUCHSX, ""},
    // {"hw.touchsy", G_TYPE_INT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_HW_TOUCHSY, ""},
    // {"hw.igain", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_HW_IGAIN, ""},
    // {"hw.colorcal", G_TYPE_STRING, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_HW_COLORCAL, ""},
    // {"hw.sntempcal", G_TYPE_UINT, G_PARAM_READWRITE | G_PARAM_CONSTRUCT, UNIT_HW_SNTEMPCAL, ""},
    {NULL, }
};